language: node_js
node_js:
  - 12
env:
  global:
    # 我将其添加到了travis-ci的环境变量中
    - GH_REF: github.com/zhangwang945/zhangwang945.github.io.git

script:
  - hexo clean  #清除
  - hexo generate #生成
after_script:
  - git clone https://${GH_REF}
  - cd ./dist
  - cp -r ../zhangwang945.github.io/.git .git
  - git init
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - master
